name: api_data
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mongo_dart: ^0.10.5
  dart_jsonwebtoken: ^3.3.1
  dart_frog: ^1.2.6

dev_dependencies:
  lints: ^6.0.0
